### ISSUE TITLE
萌享水区评10活跃度并签到.py 文件报错

### ISSUE THREAD

**Issue by KeithW0726** [wangandi520/andyspythonscript#1]
这个签到脚本在使用cookie登录的时候报错。
返回的状况是识别你是游客而不是已注册用户。

我检查了下，现在萌享cookie会有

8017a_ipstate  ip检查（这点很奇怪，值是时间戳）
8017a_ol_offset 偏移量 检查

比较难搞了，LZ你看看能否修改下

**Comment by wangandi520** [comment]
应该不会吧，我的脚本这几天还在正常运行啊。看看浏览器信息复制对没，要匹配起来。
