### ISSUE TITLE
Feat：新特性增加申请

### ISSUE THREAD

**Issue by KeithW0726** [wangandi520/andyspythonscript#2]
Po主好
有一个新的特性看是否考虑能否实现：
即根据萌享信息保存成ComicInfo.xml?

漫画元数据ComicInfo.xml是能够被漫画管理软件komga和Kavita共同识别并读取应用。这样完善好的话，后期管理漫画就会省很多事情。

初步实现设想：
1. 取数据：从文件名或者萌享标准化的名字进行格式化取数，如果数据不全进一步制定bangumi网站搜索取数
2. 漫画压缩处理：从文章上说是cbz与cb7能读取此漫画元数据文件，不确定其他格式是否读取，我初步调研的是zip也支持（毕竟跟cbz没啥区别），rar待进一步调研。必要情况则对压缩包格式进行处理。
3. 根据格式生成`xml`格式文件，并将文件移到漫画压缩包内。
3.1 应该是按照分卷的进行放入文件

参考资料：
https://moeshare.cc/read-htm-tid-275776.html

**Comment by wangandi520** [comment]
好的，我研究下，这俩软件还没用过，不过根据文件名得到的信息不多，感觉直接用everything搜索还效率更高，pc看的话推荐neeview

**Comment by wangandi520** [comment]
简单弄了一个，不过感觉作用不大，联网爬虫要获取到准确的信息也不太容易

图片压缩包内添加ComicInfo.xml（拖拽，仅文件夹）.py

给漫画压缩包添加ComicInfo.xml
仅拖拽文件夹，文件夹内是需要添加ComicInfo.xml的压缩包
符合以下条件才会运行脚本
1. 文件名要求格式[书名][作者][出版社][扫者]册数.扩展名
2. 压缩包内不含文件夹时，而且没有ComicInfo.xml
3. 文件夹内的文件[书名][作者]都一致
4. 文件扩展名fileType = ['.cbz', '.zip']

**Comment by KeithW0726** [comment]
不好意思忙 晚看，感谢增加，回头我也看看如何融合到流程中
